name: Tests

on: [ push ]

permissions: read-all

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "8.1", "8.2" ]

        name: PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress --no-interaction --no-suggest

            -   name: Execute tests
                run: php ./vendor/bin/pest --colors=always
