name: Tests

on:
    push:
    pull_request:
    workflow_dispatch:

permissions: read-all

jobs:
    tests:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: true
            matrix:
                php: [ "8.1", "8.2" ]

        name: PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    submodules: true

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv, json, dom, curl, libxml, fileinfo, tokenizer, xml
                    coverage: none

            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress --no-interaction --no-suggest

            -   name: Application code-style testing
                run: php ./vendor/bin/pest --colors=always
