name: Tests

on: [ push ]

permissions: read-all

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "8.1", "8.2", "8.3", "8.4", "8.5" ]
                pest: [ "2.0", "3.0", "4.0"]
                exclude:
                    - pest: "2.0"
                      php: "8.2"
                    - pest: "2.0"
                      php: "8.3"
                    - pest: "2.0"
                      php: "8.4"
                    - pest: "2.0"
                      php: "8.5"
                    - pest: "3.0"
                      php: "8.1"
                    - pest: "4.0"
                      php: "8.1"
                    - pest: "4.0"
                      php: "8.2"

        name: PHP ${{ matrix.php }}, Pest ${{ matrix.pest }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Install dependencies
                run: composer require pestphp/pest:^${{ matrix.pest }} -W --prefer-dist --no-progress --no-interaction --no-suggest

            -   name: Execute tests
                run: php ./vendor/bin/pest --colors=always
